### ISSUE TITLE
Firmware Revision Date Screen

### ISSUE THREAD

**Issue by aprsandrew** [aprsworld/rdlUniversal#3]
Would be useful to have a screen in the main loop that shows the firmware revision date.  Currently the only way to view that is to connect to the logger with the rdlUniversalDownload software, or to look in the 'rdLoggerCellStatus' table in MySQL if there is live data available.  

Used to be able to see the rev. date during boot-up, but it no longer does that.

**Comment by kb0thn** [comment]
implemented in Theis branch
